#!/bin/bash

#A SCRIPT THAT WILL SAVE THE USERS CURRENT CONFIGURATION

#USER VARIABLES
BACKUP_PATH='/home/david/Dropbox'
NOW=$(date +%F)

#How to restore applications from a previous build or after data loss 
#sudo dpkg --clear-selections 
#sudo dpkg --set-selections < PATH_TO_STATE_FILE
#sudo apt-get update && sudo apt-get dselect-upgrade
#optionally run sudo apt-get autoremove to remove redudant packages

#Save the current state of the systems packages
cp /etc/apt/sources.list "$BACKUP_PATH/sources.list.$NOW"
dpkg --get-selections > "$BACKUP_PATH/application-selection-state_$NOW"
