#!/bin/bash

#A SCRIPT THAT WILL SAVE THE USERS CURRENT CONFIGURATION

#USER VARIABLES
NOW=$(date +%F)
BACKUP_PATH='/home/david/Dropbox'
DST_FOLDER="$BACKUP_PATH/desktop-backup.$NOW"


#How to restore applications from a previous build or after data loss 
#sudo dpkg --clear-selections 
#sudo dpkg --set-selections < PATH_TO_STATE_FILE
#sudo apt-get update && sudo apt-get dselect-upgrade
#optionally run sudo apt-get autoremove to remove redudant packages

#Save the current state of the systems packages
mkdir $DST_FOLDER
cp /etc/apt/sources.list "$DST_FOLDER/"
dpkg --get-selections > "$DST_FOLDER/application-selection-state"
